const menu = [
    // {
    //     path: 'clientCreate',
    //     title: 'Создать Заказчика',
    //     icon: 'note_add',
    //     exact: false,
    //     permission: 'Создание Заказчиков',
    // }, {
    //     path: 'clients',
    //     title: 'Список заказчиков',
    //     icon: 'receipt',
    //     exact: true,
    //     permission: 'Просмотр Заказчиков',
    // },
    // {
    //     path: 'events',
    //     title: 'Календарь мероприятий',
    //     icon: 'event',
    //     exact: true,
    //     permission: 'Просмотр Мероприятий',
    // },
    // {
    //     path: 'archive',
    //     title: 'Архив мероприятий',
    //     icon: 'archive',
    //     exact: true,
    //     permission: 'Просмотр Мероприятий',
    // },
    // {
    //     path: 'coordinations',
    //     title: 'Согласования',
    //     icon: 'how_to_vote',
    //     exact: false,
    //     permission: 'Просмотр Мероприятий',
    // },
    // {
    //     path: 'accountancy',
    //     title: 'Бухгалтерия',
    //     icon: 'account_balance',
    //     exact: false,
    //     permission: 'Выставление счета',
    // },
    // {
    //     path: 'reports',
    //     title: 'Отчёты',
    //     icon: 'report',
    //     exact: false,
    //     permission: 'Заполнение отчетов КК',
    // },
    // {
    //     path: 'offers',
    //     title: 'Предложения',
    //     icon: 'local_offer',
    //     exact: false,
    //     permission: 'Создание предложений',
    // },
    // {
    //     path: 'settings',
    //     title: 'Настройки',
    //     icon: 'settings',
    //     exact: false,
    //     permission: 'Просмотр настроек',
    // },
];
export default menu;